blank_issues_enabled: false
contact_links:
  - name: Releases
    url: https://github.com/Zerbu/Mod-Constructor-5/releases
    about: Before submitting an issue, please verify you have the latest version of Mod Constructor.
